### ISSUE TITLE
Cant' get `__years` to work programmatically

### ISSUE THREAD

**Issue by jfilter** [datenguide/datenguide-backend#11]
The `__years` suffix works in the query editor. However, I can't get it to work when making requests programmatically e.g. with Python. How do I use it?

```
import requests
url = "https://api.datengui.de/?query={region(id:\"1\"){id name GEM001__years}}"
r = requests.get(url)
data = r.json()
print(data)
```
prints: 
`{'errors': [{'locations': [{'line': 1, 'column': 25}], 'message': 'Field "GEM001__years" of type "Region__GEM001__years" must have a sub selection.'}]}`

**Comment by simonwoerpel** [comment]
as the error message says, you need to have a sub selection. the query ui does this magically ;)

try this:

```python
requests.post('https://api.datengui.de', data={"""
{
  region(id: "01") {
    id
    name
    BEVSTD {
      ALTX20 {
        INSGESAMT {
          GEST__years {
            _2013
            _2014
            _2015
          }
        }
      }
    }
  }
}"""})
```

**Comment by jfilter** [comment]
I though that there would be a way to automatically get all available fields as well. So I guess I first have to look up what fields are available and then build my query, right?

With e.g.:
```
{
  __type(name: "Region__BEVSTD__ALTX21__ALT000B03__NAT__NATD__GEST__years")
    {
    name
    fields {
      name
    }
  }
}
```

**Comment by simonwoerpel** [comment]
yes exactly. :+1:

actually the "documentation explorer" on the upper right of the graphical query ui does exactly these queries under the hood to obtain available fields & stuff.

**Comment by jfilter** [comment]
Okay, thanks!
