### ISSUE TITLE
`geo.bbox` returns string instead of array

### ISSUE THREAD

**Issue by sjockers** [datenguide/datenguide-backend#14]
The API has recently started to return strings instead of arrays for the `geo.bbox` property. 

Demo: 
https://api.datengui.de/?query=%7B%0A%20%20region(id%3A%20%2210041%22)%20%7B%0A%20%20%20%20geo%20%7B%0A%20%20%20%20%20%20bbox%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

Expected result: 
```
{
  "data": {
    "region": {
      "geo": {
        "bbox": [6.711, 49.112, 7.137, 49.378]
      }
    }
  }
}
```

Actual result: 
```
{
  "data": {
    "region": {
      "geo": {
        "bbox": "[6.711, 49.112, 7.137, 49.378]"
      }
    }
  }
}
```

This requires [a workaround](https://github.com/datenguide/datenguide-frontend/commit/6a6ba44bec58a5a3edc64a909357c0eaf50d211d) on the client side.

**Comment by simonwoerpel** [comment]
its fixed now, so the workaround should be rolled back now :see_no_evil:

**Comment by sjockers** [comment]
👍👍👍
