### ISSUE TITLE
v2 / Always start graphiql with example query 

### ISSUE THREAD

**Issue by P3nny** [datenguide/datenguide-backend#21]
To give the user an idea of what to do with the api: 

```
{
   region(id:"07131") {
    name
    LBZ001(GESMF: "GESMF01") {
      value
      year
      GESMF
      QUARTG
      ERW122
      ELEGP1
    }
  }
}
```

**Comment by simonwoerpel** [comment]
I guess, to achieve that, we need to hook into graphiql itself, in the react component that this flask view uses, you can specify an ínitial query:
https://github.com/graphql/graphiql#usage

the easy solution would be, whenever we link to the api from the datengui.de website, we just use a link with an example query like this: [go to our cool api](https://api.genesapi.org/?query=%7B%0A%20%20region(id%3A%20%2207131%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20LBZ001(GESMF%3A%20%22GESMF01%22)%20%7B%0A%20%20%20%20%20%20value%0A%20%20%20%20%20%20year%0A%20%20%20%20%20%20GESMF%0A%20%20%20%20%20%20QUARTG%0A%20%20%20%20%20%20ERW122%0A%20%20%20%20%20%20ELEGP1%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
