### ISSUE TITLE
Duplicate districts

### ISSUE THREAD

**Issue by sjockers** [datenguide/datenguide-backend#4]
Some districts, such as Bamberg are listed twice. Probably because there is both a city and a district of Bamberg. Both share the same slug.

![screen shot 2018-02-24 at 19 20 46](https://user-images.githubusercontent.com/449739/36633564-5b0b5bca-1998-11e8-8c22-163fe4484c83.png)

**Comment by simonwoerpel** [comment]
solved: https://github.com/datenguide/datenguide-backend/commit/f45e5b97812fee3110ea62af6a5476bda8ecaf7e :heavy_check_mark:
