### ISSUE TITLE
How do I map from a `Merkmal` to a type and vice versa?

### ISSUE THREAD

**Issue by jfilter** [datenguide/datenguide-backend#9]
E.g., how do I know what means what in here? I am especially interested in a human-readable description of each type.
```
{
  region(id: "14522") {
    id
    name
    BEVSTD {
      ALTX21 {
        ALT075B80 {
          NAT {
            NATA {
              GESM__years {
                _2013
                _2011
                _2014
                _2012
                _2015
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by simonwoerpel** [comment]
yes, thats a missing feature that i am working on currently, stay tuned. :)

**Comment by simonwoerpel** [comment]
we have now this: https://github.com/datenguide/datenguide-backend/issues/10

descriped here: https://github.com/datenguide/datenguide-backend#how-to-query-keys-info

this is a start, we are also working on a nice rendering of the available `Merkmale` in the live api.

**Comment by jfilter** [comment]
Thanks!

**Comment by jfilter** [comment]
sorry, that I once again have  question

So I get these results but I am unable to understand the letter combinations. Some are `Merkmale` e.g. `ALTX21` or `NAT` and I get the description with #10. But what is `NATD` and where do I information about it?

> [{'id': '05316', 'name': 'Leverkusen', 'BEVSTD': {'ALTX21': {'ALT050B55': {'NAT': {'NATD': {'GEST__years': {'_2015': 12423.0, '_2011': 11375.0, '_2012': 11689.0, '_2014': 12375.0, '_2013': 12035.0}}}}}}}, {'id': '05366', 'name': 'Euskirchen', 'BEVSTD': {'ALTX21': {'ALT050B55': {'NAT': {'NATD': {'GEST__years': {'_2015': 16883.0, '_2011': 15406.0, '_2012': 15819.0, '_2014': 16761.0, '_2013': 16448.0}}}}}}}]

**Comment by simonwoerpel** [comment]
good point, we will have a look into it. specifically for `NATD` i can say, this is the amount of people with german nationality (`NAT` + `D`)
